### ISSUE TITLE
Generates the Error: TypeError: int() argument must be a string or a number, not 'NewId' 

### ISSUE THREAD

**Issue by kingsleyuk2003** [muk-it/muk_dms#1]
Hi;
Thanks for the module on dms. However during testing, i discovered the following error, when trying to add a file in a directory. 
![selection_004](https://cloud.githubusercontent.com/assets/1262044/25733942/127932ae-3156-11e7-89b4-eddc97fee087.png)

**Comment by kingsleyuk2003** [comment]
Also, update your documentation to allow inform users install the python mammoth library, using: sudo pip install mammoth

**Comment by keshrath** [comment]
Thx for the feedback! It should work now properly.
