### ISSUE TITLE
Access Right

### ISSUE THREAD

**Issue by palikollar** [muk-it/muk_dms#10]
If you have a user group (Documents / User) obviously it has access rights. 

How can you connect the user group in the access control panel? I saw the option for it but it doesn't show or connect with the previously created (Document / User ) group. 
I would like to give this group permissions to Read,  Write, Create or Delete some directories.

**Comment by palikollar** [comment]
#1 I have added access rights to a group Documents / User

![access_rights_user](https://user-images.githubusercontent.com/23060960/28212109-33e8d04e-68a0-11e7-8fa4-297cb9b41b68.PNG)

#2 This is the specific user in the group
![users_user](https://user-images.githubusercontent.com/23060960/28212147-54044f70-68a0-11e7-9742-a2b4c4e4cc61.PNG)

#3 I have created an access control 
![it_access](https://user-images.githubusercontent.com/23060960/28212165-692a2dca-68a0-11e7-8e5e-9f8aa91fcae3.PNG)

#4 I have added the Access control to the folder I want to make visible for Documents / User group
![it_dir_access](https://user-images.githubusercontent.com/23060960/28212185-8a3a9b4e-68a0-11e7-8012-5329f358ea24.PNG)

#5 I have set the it[at]sth.com to have user rights 
![dashbord_documents_user](https://user-images.githubusercontent.com/23060960/28212235-bd3c79cc-68a0-11e7-8f57-74407169119c.PNG)
 
My issue is that with the it account I can only see the folders if it is set to manager in step #5 and I am able to see all the folders which I don't want...only specific folders I made permission to

**Comment by keshrath** [comment]
Hi, the reason is that the manager has no access control, so he can see everything regardless of his access rights. To set the access for groups you have to create a new "muk_dms_access.groups" group.
