### ISSUE TITLE
bug odoo12: i have install muk_dms but when i install muk_dms_view, i can not open muk_dms

### ISSUE THREAD

**Issue by fnguena** [muk-it/muk_dms#106]
Hello, i have this bug when i install muk_dms_view. error below....
![error](https://user-images.githubusercontent.com/12985085/61285224-6f9ea600-a7b8-11e9-97e5-85ad3a7f545b.png)

**Comment by keshrath** [comment]
Javascript error messages without debug mode (?debug=assets) are unfortunately not sufficient to make any kind of interpretation.

**Comment by fnguena** [comment]
when i activate this mode : ?debug=assets no link works
you have an email ? I send access to a database

**Comment by keshrath** [comment]
Do you see an error in your browser console?

**Comment by fnguena** [comment]
error in console
![error](https://user-images.githubusercontent.com/12985085/61288112-5ef12e80-a7be-11e9-8a9c-ccd85326cfdc.png)

**Comment by keshrath** [comment]
web.bootstrap.extension is the problem

**Comment by keshrath** [comment]
I don't think this is dms related

**Comment by fnguena** [comment]
OK thanks, and please how can i solve it...

**Comment by keshrath** [comment]
I still dont know the error:

![image](https://user-images.githubusercontent.com/4851083/61307127-0b96d480-a7ee-11e9-985c-ed0485f0ab89.png)

**Comment by fnguena** [comment]
Thank, i have solve the bug...
the problem came from the unversioned lib folder
