### ISSUE TITLE
document sub menu not show in dms

### ISSUE THREAD

**Issue by movahhed** [muk-it/muk_dms#108]
hi dear 
cant see tree view in muk dms  please help me 
![Untitled](https://user-images.githubusercontent.com/27208274/62427218-d1419880-b704-11e9-92ba-b3dd9b40421f.jpg)
](url)

**Comment by keshrath** [comment]
I don't understand the problem on the basis of the information. You may have to create a file to see one.

**Comment by movahhed** [comment]
![Screenshot_20190805-002158](https://user-images.githubusercontent.com/27208274/62428426-179ff300-b717-11e9-9f5c-736590c38cdd.jpg)
Tree view similar this

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/tree/12.0/muk_dms_view
