### ISSUE TITLE
could not find client action"muk_dms_views.documents"

### ISSUE THREAD

**Issue by smaryam** [muk-it/muk_dms#110]

**Comment by jbulbule** [comment]
I installed this module on my localhost Odoo V11 CE. Installation was successful for the main and all submodules. But, when I get into "Document" module I get an error on clicking the "Document" menu there. Error: "Action Error - Could not find client action 'muk_dms_views.documents". What could I have done wrong?

As suggested on apps.odoo.com, I also tried with cleaning the browser cache and restarting the server. But no gain.

I also checked the log file but it has nothing related to this error.

![muk_dms_error](https://user-images.githubusercontent.com/37848001/62962233-245dce80-be1c-11e9-8d64-6572df2cafa4.png)

**Comment by keshrath** [comment]
Check if Odoo has the correct access right on the OS for the addons folder.

**Comment by jbulbule** [comment]
Nope! Access rights solution didn't work. My addons is in /opt/odoo/odoo11/addons/ and I gave accesses as below -

chmod -R 777 /op/odoo/
chown -R odoo: /opt/odoo/

**Comment by kalmat48** [comment]
Hello,
I have a same problem as jbulbule.
I've configured a fresh instance of Odoo 11ce on debian machine and added muk.dms module
from odoo apps site. Everything works fine, but when I click on Document menu I get the same
error: "Action Error - Could not find client action 'muk_dms_views.documents".

Access rights are OK, so I tried another thing. I configured Odoo 11ce on my local Ubuntu
machine (all access rights on addons folders are my login user). Same error occures.
 
Than I tried another thing. I downloaded muk.dms from this github and also added dependencies
muk_base and muk_web. It didn't helped.

So what else could be wrong.

**Comment by bennals** [comment]
@jbulbule @kalmat48 @keshrath @Kerrim- 

I was having this exact same problem after recently doing a complete update of all the muk modules I have installed (Ubuntu 16.04, Odoo V11 CE).

I happened to have a test server which had most of the modules updated (but didn't get the full update treatment) and it wasn't displaying this error.  

I discovered that I had version 11.0.2.0.17 of muk_web_utils installed on that server rather than 11.0.2.0.19 which was the latest update on the server exhibiting the problem.

I rolled the version of muk_web_utils back to 11.0.2.0.17 and the error has stopped occurring and the tree view appears to be functioning normally.

Perhaps something has gone awry between 17 and 19?

**Comment by kalmat48** [comment]
Thank you @bennals!

I've downloaded muk_web branch 11.0.2.0.17, restarted the server
and the tree view on 'Documents' menu is working.

@jbulbule try this solution!

**Comment by LucianoCM75** [comment]
Prezados, boa tarde...

Onde posso baixar essa versão do muk_web branch 11.0.2.0.17? Pois no site da Odoo não encontrei!!

Where can I download this version of muk_web branch 11.0.2.0.17? Because on Odoo's website I didn't find it !!

**Comment by bennals** [comment]
Use the "History" button and then the "<>" button to browse the repository at a point in time when muk_web_utils was at version 11.0.2.0.17.

https://github.com/muk-it/muk_web/tree/72c336d7d8b05058c8285c72d9888901bfc7373c

**Comment by keshrath** [comment]
@Kerrim- Please can you check what has gone wrong between 17 and 19?

**Comment by LucianoCM75** [comment]
Prezados, boa tarde...

Vocês sabem onde fica para baixar o ADD "muk_web branch" para a versão também do Odoo 10 e da versão Odoo 12, que também não apresentem esse erro?

Dear, good afternoon ...

Do you know where it is to download the "muk_web branch" ADD for the Odoo 10 and Odoo 12 versions as well, which also do not have this error?

**Comment by LucianoCM75** [comment]
Prezados, boa tarde...

Como faço para atualizar minha versão do Odoo 10 para o Odoo 11ou 12 no windows 10?


Dear, good afternoon ...

How do I upgrade my version of Odoo 10 to Odoo 11or 12 on windows 10?

**Comment by LucianoCM75** [comment]
Eu consigo usar o OpenUpgrade no windows 10?

Can I use OpenUpgrade on windows 10?

**Comment by Hashim-Khalid** [comment]
guys i have this problem in odoo 13 and muk_web branch 11.0.2.0.17 doesn't solve it

**Comment by keshrath** [comment]
Odoo13 isn't support at the moment
