### ISSUE TITLE
Interaction with Website App

### ISSUE THREAD

**Issue by miguelsilvazup** [muk-it/muk_dms#115]
I am using the Website app to create a panel for some Portal Users. A few icons must be linked to specific directories, allowing them to access the files. There are two different sorts of access:

1. an icon must connect to a common directory everyone will have access;
2. other two icons will connect to specific directories (names: Forponto and Certificates) inside the specific user directories.

I could not create any link that works for Portal Users, even changing Access Groups in Documents or the Groups for Users. Is this a problem about Groups and Permissions or Documents does not allow any interaction with Sites?

**Comment by keshrath** [comment]
The DMS in its current form has no portal integration. This is on our roadmap but I can't tell you when it will happen.
