### ISSUE TITLE
Error: QWeb2: Template 'DMSTreeView' not found

### ISSUE THREAD

**Issue by VincentSurelle** [muk-it/muk_dms#12]
Hi,

I'm trying to install Muk DMS on my Odoo instance but once installed it throw me an error `Error: QWeb2: Template 'DMSTreeView' not found` when I click on `Documents` tab. The only way to get out is to close my browser tab.

To install it I cloned the git repo into my addons folder

```
/mnt/extra-addons/muk_dms
```

And then I went to Oddo application's to install it.

I'm using `odoo:10` docker image. And I installed Mammoth in it.

**Comment by rizzopablo** [comment]
Same here

**Comment by bnjroos** [comment]
Same here, any fix ?

**Comment by keshrath** [comment]
Can you give me more Infos :) please try it in debug mode (debug=assets) and check your browser console and your Odoo logs

**Comment by crsilveira** [comment]
Error: QWeb2: Template 'DMSTreeView' not found

Action Error: Could not find client action muk_dms.tree_view

**Comment by xwjh** [comment]
me too

**Comment by davinci41** [comment]
me too. please help

![image](https://user-images.githubusercontent.com/25403547/29744159-7f79db04-8a9f-11e7-9e77-5e1eb3b8a346.png)

**Comment by dceevp** [comment]
Same error.
On local VPS work well. 
I install it on amazon EC2, then the plugin show the error (I hide the IP)

http://-------/web/content/251-bbdd526/web.assets_common.js:2908
Track error:
Error: QWeb2: Template 'DMSFieldPath' not found
   at QWeb2.tools.exception (http://------/web/content/251-bbdd526/web.assets_common.js:2908:1)
   at _render (http://------/web/content/251-bbdd526/web.assets_common.js:2953:85)
   at render (http://-------/web/content/251-bbdd526/web.assets_common.js:2949:140)
   at renderElement (http://--------/web/content/251-bbdd526/web.assets_common.js:3113:1062)
   at renderElement (http://------/web/content/412-88b3ab4/web.assets_backend.js:2221:2957)
   at Anonymous function (http://-------/web/content/251-bbdd526/web.assets_common.js:3010:548)
   at renderElement (http://------/web/content/412-88b3ab4/web.assets_backend.js:2227:1457)
   at Anonymous function (http://-------/web/content/251-bbdd526/web.assets_common.js:3010:548)
   at Anonymous function (http://--------/web/content/251-bbdd526/web.assets_common.js:3113:912)
   at Anonymous function (http://-------/web/content/251-bbdd526/web.assets_common.js:547:661)


Other info

-Apache proxy config to hide port :8069
-chown -R odoo:odoo /odoo/

**Comment by keshrath** [comment]
Does this issue still exists in version 1.0.2?

**Comment by dceevp** [comment]
hi, I will try this new version.

**Comment by gsputro** [comment]
Hi @keshrath, I'm still facing this issue.
I download it from [here](https://www.odoo.com/apps/modules/10.0/muk_dms/)

When I unzip the module, it asked me to replace some other files on the other dependencies modules such as: MUK Preview, Web Client, Web Refresh. Should I choose Replace or not?

And could you please inform us what's the best option to install those dependencies which module should be installed first and the next after?

Yeah, I've just tried this module on Amazon EC2 as well, same with @dceevp 

Appreciate your feedback.

Thanks
-gs

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_web/archive/10.0.zip
https://github.com/muk-it/muk_dms/archive/10.0.zip

**Comment by keshrath** [comment]
![image](https://user-images.githubusercontent.com/4851083/31850511-63c8ca70-b653-11e7-9da6-e3b3aae4d750.png)

**Comment by keshrath** [comment]
Hi,
can you please send me your error log with debug=assets :)

**Comment by davinci41** [comment]
I installed the latest version and when it comes into the module such something appears.

Is there any installation guide?

![image](https://user-images.githubusercontent.com/25403547/32136772-2ec62892-bc14-11e7-8fbd-d07902b38237.png)

**Comment by keshrath** [comment]
Hi i can't say much without an error log. Please look at my posts above.

**Comment by gsputro** [comment]
Hi @keshrath,

Thanks for your feedback, Please find attached in the link below is the screenshot of the 'debug' mode.
http://take.ms/D6gDK

I've solved this by chown -R odoo:odoo for all files underneath your addons modules and then restart the Odoo service.

But, I found another issue.
The file preview didn't work. I couldn't see the 'preview' symbol to the Attachment button on the 'Project' form in this case. Please refer to image attached below.

Thank you
-gs
![screenshot-54 254 178 158-8080-2017-10-29-10-01-06-732](https://user-images.githubusercontent.com/2078953/32140343-e73d0194-bc90-11e7-87af-319357831c2e.png)

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_web/tree/11.0/muk_web_preview_attachment

**Comment by keshrath** [comment]
Have you installed this app?

**Comment by davinci41** [comment]
@keshrath I restarted the odoo and it is ok

**Comment by gsputro** [comment]
@keshrath - I have installed that app. Please find attached in this link below is the app and add-on that have been installed in our Odoo instance.
http://take.ms/dqvyc

Thanks
-gs

**Comment by keshrath** [comment]
Looks to me like you are missing the app. See the link above.

**Comment by gsputro** [comment]
@keshrath Sorry, I didn't notice that was a different app. With "File Preview Dialog" app. Thank you. All good and solved now.

**Comment by LuisFcoOrtiz** [comment]
Restarting the odoo server I can fixed the error [/etc/init.d/odoo restart] (in linux)

**Comment by Hamza-MESRAR** [comment]
I had the same problem but I found the solution must be changed the privilege like chmod 777 /folder and chown odoo:odoo /folder

**Comment by LuisFcoOrtiz** [comment]
How @Hamza-MESRAR says, it's also true!

**Comment by Gelson15** [comment]
I'm trying to install Muk DMS on my Odoo instance, but once installed, it throws me an error Error: ImportError: No module named 'models'

**Comment by Hamza-MESRAR** [comment]
can you make screen about that?

**Comment by keshrath** [comment]
@Gelson15 Have you tried restarting your server? If not, try updating the module again and then restart the server. If this is not useful, I need more information (server and browser log with debug=assets)

**Comment by Gelson15** [comment]
thank you very much for your reply keshrath, I can solve the problem, now when I click on install my environment appears white, meno and the application does not appear

**Comment by Gelson15** [comment]
I think it's through this message that:
"cabosysdb odoo.addons.sms.wizard.send_sms: The `phonenumbers` Python module is not available. Phone number validation will be skipped. Try `pip3 install phonenumbers` to install it."

**Comment by Hamza-MESRAR** [comment]
you should restart your server

**Comment by Gelson15** [comment]
I do it, I stop my execution I make the changes and I put the execution fee again but the error is continuing

**Comment by Hamza-MESRAR** [comment]
can you verify the privilege about your module chown and chmod

**Comment by Gelson15** [comment]
how can I do this ? Hamza-MESRAR

**Comment by Hamza-MESRAR** [comment]
If you use Linux you must check user about your module for exemple :
Chmod -R 777 /your_module and
Chown -R odoo:odoo /your_module
Odoo name of user

**Comment by Gelson15** [comment]
Hamza-MESRAR, thank you very much for your help and for what you are doing for me.

**Comment by Gelson15** [comment]
I am developing another module, I would like to load data from a table, deferential module and present in the form of the module. I would like to know if this is possible in odoo, and how can I solve this problem.

**Comment by Hamza-MESRAR** [comment]
yes you can

**Comment by Gelson15** [comment]
I would like to have a suggestion how can I do this

**Comment by Gelson15** [comment]
I have Odoo Development Essentials but it is not enough for the development odoo, you have some suggestion where I can find more complete documents or contiudos for the odoo developer. Thank you.

**Comment by Hamza-MESRAR** [comment]
in odoo official documentation

**Comment by Gelson15** [comment]
How to extract data from the SQL query and assign it to the columns of the Odoo class?

Could anyone provide valuable information about this? how to get those values ​​in Odoo class columns (I meant assign to fields that of the class) and also how to get columns from two tables.

**Comment by mrezki** [comment]
for me it is still be issue.

![selection_111](https://user-images.githubusercontent.com/7223494/49684881-930bbf00-fb0c-11e8-8013-d63379f83722.png)

![selection_112](https://user-images.githubusercontent.com/7223494/49684905-e3831c80-fb0c-11e8-89f4-306a51e9abfb.png)


error is solved. but pdf not render on the page preview like this:

![selection_113](https://user-images.githubusercontent.com/7223494/49688189-e0098880-fb40-11e8-8262-825f549354f3.png)

can you help me please.
