### ISSUE TITLE
[12.0] muk_dms: Filestore

### ISSUE THREAD

**Issue by Slivi-sliv** [muk-it/muk_dms#131]
Hi,
I recently installed MUK_DMS.
I have files stored in directories on the disk (on the server). I would now like to display these files and directories in the application. Is this possible?
Is it possible to set a location for Filestore and sync it?
Thank you.

**Comment by Slivi-sliv** [comment]
Any suggestion?

**Comment by keshrath** [comment]
Hello, no this is not the purpose of the muk_dms_file module. There is no bidirectional sync.
