### ISSUE TITLE
Error installing module 'muk_dms' that depends on module 'muk_security'

### ISSUE THREAD

**Issue by HugoDelval** [muk-it/muk_dms#139]
Hi,

I'm trying to install the Muk Documents (`muk_dms`) module by adding your repository to my addons.

![image](https://user-images.githubusercontent.com/9109308/78376617-dd9d2e80-75ce-11ea-916e-7f482d7e7311.png)

But I get an error, saying that the `module 'muk_dms' depends on module 'muk_security'`

![image](https://user-images.githubusercontent.com/9109308/78376676-f0176800-75ce-11ea-8817-c2629d205082.png)

https://github.com/muk-it/muk_dms/blob/12.0/muk_dms/__manifest__.py#L36

Do you have any idea of what's going on? Should I install the module in another way?

Thanks in advance, have a good weekend.

**Comment by HugoDelval** [comment]
Ah! It looks like the module is available here: https://github.com/muk-it/muk_base/tree/12.0

If you want I'd be glad to open a PR explaining this in the README :)

**Comment by loredev10** [comment]
> You also need addons from https://github.com/joyinfo/muk_base and https://github.com/joyinfo/muk_web.

https://github.com/muk-it/muk_dms/issues/135#issuecomment-641237761
