### ISSUE TITLE
mammoth external dependency is not met (odoo)

### ISSUE THREAD

**Issue by IBAMS** [muk-it/muk_dms#16]
I try to install  "muK dms" but requires a module "mammoth". I installed  mammoth in cmd.exe with C:\python36\python -m pip install mammoth. 
Answer:
Requirement already satisfied: mammoth in c:\python36\lib\site-packages
Requirement already satisfied: cobble<0.2,>=0.1.2 in c:\python36\lib\site-packages (from mammoth)

But I got the same answer from odoo:
Unable to install module "muk_dms" because an external dependency is not met: No module named mammoth

 I don't know where or how to install mammoth, the only place where python is installed is c:\python36, any help?

**Comment by MuKGexi** [comment]
have you tried installing it by writing pip install mammoth into your command line?

**Comment by IBAMS** [comment]
Yes I did it, but it did not work with pip only. with  'C:\python36\python -m pip install mammoth' into the command line it was successfully installed. A new type I got the Answer:

Requirement already satisfied: mammoth in c:\python36\lib\site-packages
Requirement already satisfied: cobble<0.2,>=0.1.2 in c:\python36\lib\site-packages (from mammoth)

it seems to be installed correctly.

**Comment by keshrath** [comment]
Could it be that you have python 3 installed aswell? It looks like you installed mammoth into your python 3 directory. Odoo is runing with python 2 so make sure to install it on python 2.

**Comment by IBAMS** [comment]
Thanks, that was the problem I had Python 3.6 installed. Now it works.
