### ISSUE TITLE
Connection lost while wanting to add new file

### ISSUE THREAD

**Issue by bnjroos** [muk-it/muk_dms#21]
Hi,

I have been able to add 5 documents but now whenever I want to check out or save I get a connection lost error and can't proceed forward. Any hint on that issue ?

Best regards,

Bnjroos

**Comment by bnjroos** [comment]
It seems that the size of the file is a problem (800ko). 
Console log:
Failed to load resource: the server responded with a status of 413 (Request Entity Too Large) /web/dataset/call_kw/muk_dms.file/create

**Comment by keshrath** [comment]
How big is your file?

**Comment by bnjroos** [comment]
Around 800kb.

**Comment by keshrath** [comment]
800kb should be fine, the limit is currently set to 25mb. It could be that your nginx or apache server is blocking the file.
