### ISSUE TITLE
Using the module in the WebSite

### ISSUE THREAD

**Issue by j-l-santiago** [muk-it/muk_dms#22]
I can not find documentation on how to use the module on the WebSite. I would like that the authentified users can acces to several Download and preview directories and to search files.

Is there something similar build in in the module?

Should I develop a extension to do that?

**Comment by keshrath** [comment]
Do you mean as a portal user?

**Comment by j-l-santiago** [comment]
Yes, I mean as a portal user

**Comment by keshrath** [comment]
right now there is no website module for the dms, so you would need to implement it yourself.
