### ISSUE TITLE
Need to reload everytime directory and files are added

### ISSUE THREAD

**Issue by diwap** [muk-it/muk_dms#23]
When we add files or create directory, we won't be able to see them in the main view. However if we reload odoo, we will be able to see them.

**Comment by Kerrim-** [comment]
Hi,

we have a module that should fix this issue. [1]

Regards,
Kerrim Abd El-Hamed
MuK IT

[1] https://github.com/muk-it/muk_web/tree/11.0/muk_web_client_refresh

**Comment by keshrath** [comment]
Thx for the info i will look into it

**Comment by keshrath** [comment]
![image](https://user-images.githubusercontent.com/4851083/32151062-1ab66590-bd1a-11e7-98ea-b57f3390b6c3.png)

**Comment by keshrath** [comment]
does your longpolling work? cause i tested it and it works on the test system just fine.

**Comment by diwap** [comment]
yes longpolling is working in same interval of time.
