### ISSUE TITLE
added documents in tasks

### ISSUE THREAD

**Issue by davinci41** [muk-it/muk_dms#24]
Gdzie trafiaja dokumenty dodane w zadaniach. 
Dodaję dokument w zadaniach ale w dokumentach go nie widać, trzeba to ustawić?

![image](https://user-images.githubusercontent.com/25403547/32147570-f256d97a-bce9-11e7-88a7-f5ea62274fc2.png)

![image](https://user-images.githubusercontent.com/25403547/32147572-01ce47b2-bcea-11e7-9382-0bfea8983271.png)

**Comment by keshrath** [comment]
As far as google translate was able to do the job I guess I understand what you are trying to do^^

When you are adding an Attachment to your project the DMS doesn't know about it cause it is an Attachment and not a File. I will publish a module, which will create Files from Attachments, but it will take a while.
