### ISSUE TITLE
Uncaught TypeError: this.$el.find(...).split is not a function

### ISSUE THREAD

**Issue by satriani-vai** [muk-it/muk_dms#25]
![bildschirmfoto vom 2017-11-09 20-52-52](https://user-images.githubusercontent.com/5981417/32626752-7c88dfb8-c590-11e7-9746-9d7e26b8fc88.png)

**Comment by satriani-vai** [comment]
Maybe this is related to the new Postgresql version 10

**Comment by Kerrim-** [comment]
Hi, can you please provide some more information? Like what where you doing before this dialog appeared?

**Comment by satriani-vai** [comment]
Just installed this module
I got some more error messages
> Could not get content for /muk_dms/static/lib/jquery-splitter/css/jquery.splitter.css defined in bundle 'web.assets_backend'.
Could not get content for /muk_dms/static/lib/jsTree/themes/default/style.css defined in bundle 'web.assets_backend'.

**Comment by keshrath** [comment]
could it be that odoo has no right to read the folder? (/muk_dms/static/)
