### ISSUE TITLE
[11.0] Setting can't be applied

### ISSUE THREAD

**Issue by satriani-vai** [muk-it/muk_dms#26]
The settings cannot be applied.
After saving the settings, all checkboxes are not checked again.
Unfortunately, the error is not traceable in the logs.

**Comment by keshrath** [comment]
![image](https://user-images.githubusercontent.com/4851083/33989366-883daf76-e0c7-11e7-86b8-9c7a38c8a7f3.png)

Checking these settings will try to install some extra modules like muk_dms_access, but they are not ported to version 11 jet.

The version 11 Documents is still in its beta version, so it will take a few more days to port the rest of the modules.

**Comment by satriani-vai** [comment]
Alright, we will wait. Thanks for your effort.
