### ISSUE TITLE
DMS settings are not saved

### ISSUE THREAD

**Issue by maiolif** [muk-it/muk_dms#34]
In odoo 11 with mammoth, modify and save settings process is ok, no error also from terminal, but after save settings are all as before.

**Comment by keshrath** [comment]
can you give me more information: which setting? as admin or as an other user?

**Comment by maiolif** [comment]
Document -> Settings -> General Settings (i.e. Finder flag). Doing is as Administrator in a test environment. In the screenshot attached, i.e. the Finder flag was TRUE before saving
![screenshot at 2018-01-26 15 10 43](https://user-images.githubusercontent.com/10357943/35443362-1a6d6c42-02ab-11e8-9b2b-e239097ac0b4.png)

**Comment by keshrath** [comment]
All settings listed as extensions are apps. You need to have dem available on your system. Note: Finder is currently not available on the Odoo store.
