### ISSUE TITLE
After deleting a file, the information still remains unchanged

### ISSUE THREAD

**Issue by satriani-vai** [muk-it/muk_dms#36]
![image](https://user-images.githubusercontent.com/5981417/35476342-a6bda500-03ae-11e8-9480-4443e0cf1d9f.png)

PS: Kann man muk_web_views_list_switch irgendwo testen? :smiley:

**Comment by keshrath** [comment]
956f70d9a4519a550b2e6542b76d3eaf23d13e23

Leider ist es im Moment noch nicht möglich nur einzelne TreeNodes neu zu laden.

PS: Leider haben wir im Moment noch kein öffentliches Demo System.

**Comment by satriani-vai** [comment]
Zu früh geschlossen. Bei mir bleibt die Größe weiterhin unverändert :roll_eyes:

**Comment by keshrath** [comment]
Wird der View nach dem löschen automatisch neu geladen?

**Comment by satriani-vai** [comment]
Ja, sieht so aus. Hast du es selbst getestet?

**Comment by keshrath** [comment]
![image](https://user-images.githubusercontent.com/4851083/35509922-603a5940-04f6-11e8-91e6-a3fd97de4edb.png)

**Comment by keshrath** [comment]
![ezgif-4-eab9e11621](https://user-images.githubusercontent.com/4851083/35509957-7a1e229c-04f6-11e8-84d2-5b160197d856.gif)

**Comment by satriani-vai** [comment]
Merkwürdig..
Ich habe es nochmal getestet, mit dem gleichen Ergebnis

![402f24f288](https://user-images.githubusercontent.com/5981417/35511490-6af1e6ae-04fc-11e8-9764-d196f4249855.gif)

**Comment by satriani-vai** [comment]
Ich weiß nicht ob es mit den letzten commits 18c4b79 und 50acde3 zutun hat, aber es funktioniert jetzt.
Vielleicht gab es ein Abhängigkeitsproblem. Wie auch immer, Hauptsache es funktioniert :+1:

**Comment by niulinlnc** [comment]
@satriani-vai  @@keshrath
If I use the mouse to drag a file from one folder to another, the size of the folder is still not updated.
