### ISSUE TITLE
Add fields to documents

### ISSUE THREAD

**Issue by gassganso** [muk-it/muk_dms#40]
Hi,
I've been looking for the way to add extra fields or info to documents. Things like keywords, short descriptions or categories. File names are not enough for me to filter or find a document.
Is that possible to do this with muk_dms?

Thank you very much for your product.
gassganso.
(sorry if this is not the place for these questions)

**Comment by keshrath** [comment]
Hello,
in short, yes, but it depends on your programming skills. You could add a module and extend the model "muk_dms.file" according to your wishes. If you are using Odoo EE it should also be possible to add simple fields using the Studio app. Alternatively, I can suggest that you send us (sales@mukit.at) a feature request and we will be happy to send you an offer.
Regards
Mathias
