### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by Senudo-Smith** [muk-it/muk_dms#47]
After i installed the module and restarting odoo server, i get this error 
![capture](https://user-images.githubusercontent.com/40515849/42019525-46c91c08-7aad-11e8-962c-3e3d3b4b93c0.PNG)

**Comment by keshrath** [comment]
Please restart the server and update the app. If this does not fix the bug, please switch to debug mode (?debug=assets) and look into the browser console to see the bug report and send it to me.

**Comment by Senudo-Smith** [comment]
the error comes up after the module is uploaded, not after an update. It doesn't get to the update section to update the module before the error prompts

**Comment by keshrath** [comment]
Even after a server restart? Which version of Odoo is used?

**Comment by Senudo-Smith** [comment]
Yes, after server restart. I'm using Odoo 8

**Comment by keshrath** [comment]
The DMS was backportet by EL HARTI Mohamed charif <mohamed.charif.harti@gmail.com>, because I currently have no running version of odoo 8 I would ask you to contact Mohamed directly.
