### ISSUE TITLE
How to install mammoth in windows

### ISSUE THREAD

**Issue by ryuaka** [muk-it/muk_dms#5]
Hi, I'm trying to install Muk_dms, but it shows me this error: No module named mammoth. I know that mammoth is required but I really don't know how to install mammoth on windows system. Can you tell me if there a module or any other way to install it?

**Comment by keshrath** [comment]
Hi, mammoth can be installed via pip like any other python library.

pip install mammoth

![image](https://user-images.githubusercontent.com/4851083/27476341-b03021fa-5808-11e7-91c9-dc334cfca493.png)
