### ISSUE TITLE
Clear documentation

### ISSUE THREAD

**Issue by SalahAdDin** [muk-it/muk_dms#50]
I have some question about this system:
What is the logic behind the documents?
What does setting mean?
If i want to use a file system, what must i to put in the `path setting`? 

I like this module, it is very professional, good icon and good aesthetic, thank you very much.

**Comment by keshrath** [comment]
I don't really understand your first two questions. To your 3rd question: You must specify the location in your system where the Filestore should be created. Make sure Odoo has enough rights there.

**Comment by SalahAdDin** [comment]
Can we use external file storage services?

Yes, why must we create a setting before. What does it mean?

**Comment by keshrath** [comment]
We are working on modules that allow the connection to services like Amazon S3. At the moment there are only 3 storage types (DB Blob, DB Large Obejct, Filestore)

The reason for this is that it opens up more possibilities to control different types of documents. For example, you might have a Settings object in which all attachments are stored and then want to save them on a different location or not display them in the tree. However, you still want the possibility to see your other documents.

**Comment by SalahAdDin** [comment]
@keshrath I know there is other pay modules that enables storage services.

Ok, more or less i understand the aim for this setup. Thank you.
