### ISSUE TITLE
Verzeichnis kann nicht erestellt werden

### ISSUE THREAD

**Issue by satriani-vai** [muk-it/muk_dms#52]
`Datensatz existiert nicht oder kann nicht gefunden werden.`

Folgende Module sind installiert
muk_dms 11.0.2.1.4
muk_web_preview 11.0.2.1.2
muk_automation_extension 11.0.1.0.0
muk_web_client_refresh 11.0.2.1.2
muk_utils 11.0.1.0.12
muk_web_client 11.0.2.0.1
muk_security 11.0.1.1.0
muk_autovacuum 11.0.2.1.2
muk_web_utils 11.0.2.0.16
Server wurde neu gestertet

**Comment by keshrath** [comment]
Hast du logs/traceback?
