### ISSUE TITLE
Loading files not working on Firefox

### ISSUE THREAD

**Issue by jesdazrez** [muk-it/muk_dms#6]
The way you propose to use your module in the README file does not work on Firefox. Also, it appears that the text inputs are unaligned.
Chromium requires two clicks to open the file dialog.

Is it possible to place the preview widget in a form view?

Greetings.

**Comment by AfroMonkey** [comment]
In Chromium the inputs are alligned. But I have the same problems here.

**Comment by keshrath** [comment]
Hi, I updated the project. It should work now in Firefox too.
