### ISSUE TITLE
NameError: name 'vals' is not defined

### ISSUE THREAD

**Issue by jjlopezg** [muk-it/muk_dms#60]
you can check this
odoo v11

  @api.multi
    def unlink(self):
        model_recs = defaultdict(set)
        model_names = self.pool.descendants(['muk_utils.groups'], '_inherit', '_inherits')
        for model_name in model_names:
            model = self.env[model_name].sudo()
            if not model._abstract:
                model_recs[model_name] = model.search([['groups', 'in', self.mapped('id')]])
        result = super(ResGroups, self).unlink(**vals**)
        for tuple in model_recs.items():
            tuple[1].trigger_computation(['users'])
        return result

  File "G:\odoo\V11\odoo\odoo\addons\base\ir\ir_model.py", line 1627, in _process_end
    record.unlink()
  File "G:\odoo\V11\odoo\myaddons\muk_utils\models\res_groups.py", line 65, in unlink
    result = super(ResGroups, self).unlink(vals)
**NameError: name 'vals' is not defined**

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_base/commit/2390ce41d7f3e52e0448710e86574f198e557501
