### ISSUE TITLE
[11.0] muk_dms_file duplicate files on file system

### ISSUE THREAD

**Issue by Davidb34** [muk-it/muk_dms#61]
Hi, i use muk_dms_file-11.0.2.0.1 and when i set the path for the storage (as filesystem storage) it's automatically add the name of the database used. 
(ex: path that i set : /opt/odoo/NASFILES and when i save it store: /opt/odoo /NASFILES/dbname)

The problem is when i create folders (2018 and Bill)and add a file (invoice.pdf) i can find these files on the path:
/opt/odoo/NASFILES/2018/Bill/invoice.pdf
and
/opt/odoo/NASFILES/dbname/2018/Bill/invoice.pdf

so everything is in double on my path one store at "rootpath" and one in a subdirectory: dbname

Do you ever notice this issue?

thanks.

**Comment by Davidb34** [comment]
Hello, i still got this issue, i tried on new installation but it's still the same.
Can you tell me if you are looking on this?

Thanks.

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/commit/8b37981f9dc5ab962d6e1d92d84a5a8504529016
