### ISSUE TITLE
Error muk_dms.FileSiebar

### ISSUE THREAD

**Issue by danielosser** [muk-it/muk_dms#67]
Error when installing DMS module.

Error in Qweb Template, found that it's a typo in a few files. See below.
muk_dms.FileSiebar instead of muk_dms.FileSidebar

find . -print |xargs grep Siebar
grep: .: Är en katalog
grep: ./description: Är en katalog
grep: ./src: Är en katalog
grep: ./src/xml: Är en katalog
./src/xml/views.xml:	<t t-name="muk_dms.FileSiebar">
./src/xml/views.xml:	<t t-name="muk_dms.FileSiebarStarred">
./src/xml/views.xml:	<t t-name="muk_dms.FileSiebarDirectories">
./src/xml/views.xml:	<t t-name="muk_dms.FileSiebarCategories">
./src/xml/views.xml:	<t t-name="muk_dms.FileSiebarTags">
grep: ./src/img: Är en katalog
grep: ./src/img/small: Är en katalog
grep: ./src/img/original: Är en katalog
grep: ./src/img/medium: Är en katalog
grep: ./src/js: Är en katalog
grep: ./src/js/views: Är en katalog
grep: ./src/js/views/mixins: Är en katalog
grep: ./src/js/views/directory: Är en katalog
grep: ./src/js/views/directory/form: Är en katalog
grep: ./src/js/views/file: Är en katalog
grep: ./src/js/views/file/kanban: Är en katalog
./src/js/views/file/kanban/file_kanban_sidebar.js:    template: 'muk_dms.FileSiebar',
./src/js/views/file/kanban/file_kanban_sidebar.js:    	var starred = $(QWeb.render('muk_dms.FileSiebarStarred', {
./src/js/views/file/kanban/file_kanban_sidebar.js:    	var directories = $(QWeb.render('muk_dms.FileSiebarDirectories', {
./src/js/views/file/kanban/file_kanban_sidebar.js:    	var categories = $(QWeb.render('muk_dms.FileSiebarCategories', {
./src/js/views/file/kanban/file_kanban_sidebar.js:    	var tags = $(QWeb.render('muk_dms.FileSiebarTags', {

Best regards,
Daniel

**Comment by keshrath** [comment]
Thanks for the info the sidebar is still work in progress. I will fix it with the next revision.

**Comment by danielosser** [comment]
No problem. 

I did a short test of adding a document and it all works as expected. :)

Best regards,
Daniel
