### ISSUE TITLE
[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. 

### ISSUE THREAD

**Issue by Highcooley** [muk-it/muk_dms#69]
**[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead.**
[See for more details.](https://www.chromestatus.com/features/4642138092470272)
This relates to version 10.0 /muk_dms/static/lib/jsTree/jstree.js

**Comment by Highcooley** [comment]
Are you planning on working on this? Otherwise DMS for odoo 10.0 will stop working very soon. Thanks for your reply.

**Comment by keshrath** [comment]
JSTree is a library. Do you know if it is fixed there or a newer version exists?

**Comment by keshrath** [comment]
3.3.4 -> 3.3.7 might be possible and should solve this issue. If you have the time you could test it and do a PR.

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/pull/72
