### ISSUE TITLE
File storage location

### ISSUE THREAD

**Issue by rikvanlier** [muk-it/muk_dms#74]
I have a Windows version of Odoo 12 running. I installed Muk Documents and the option Filestore Storage.
 
I installed a Storage as File Storage. 
 
But where is this placed on my windows server? Where does the data goes to?

**Comment by keshrath** [comment]
same place as the Odoo filestore:

os.path.join(config.get('data_dir'), 'files', dbname)
...\AppData\Local\OpenERP S.A\Odoo\files
