### ISSUE TITLE
Cannot read property 'settingView' of undefined

### ISSUE THREAD

**Issue by luisvzqz** [muk-it/muk_dms#77]
Cannot read property 'settingView' of undefined
Gives me this as an error when trying to enter to Settings/General Setting
![Documents   System](https://user-images.githubusercontent.com/24595734/54221634-8905ad80-44b9-11e9-82b5-92f76d0a8bce.png)

Investigating furthermore I had been able to debug, the following:
fin360 odoo.schema: Table 'res_config_settings': unable to set NOT NULL on column 'attachment_location'!
If you want to have it, you should update the records and execute manually:
ALTER TABLE "res_config_settings" ALTER COLUMN "attachment_location" SET NOT NULL 

I think that this has to do with an installation of DMS Attachment, but I can not set it, because I can not enter to General Settings !!

<img width="1287" alt="Screen Shot 2019-03-12 at 11 26 22" src="https://user-images.githubusercontent.com/24595734/54221900-f74a7000-44b9-11e9-9bd5-6adc44927a3d.png">

Please HELP !!!!

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_web/issues/66
