### ISSUE TITLE
After adding muk_dms_access to my odoo/addons folders the Odoo website breaks...

### ISSUE THREAD

**Issue by palikollar** [muk-it/muk_dms#8]
I can't even get to the settings or install apps because it displays the web page like this:
![image](https://user-images.githubusercontent.com/23060960/28117002-dbab9118-670b-11e7-855a-7232d56f4dc6.png)

**Comment by keshrath** [comment]
Hi, please check your odoo and browser logs. Without more information im afraid I wont be able to help you.

**Comment by palikollar** [comment]
The server log said it couldn't find pandas package, so after installing it and restarting Odoo and PostgreSQL it works fine.
Thanks
