### ISSUE TITLE
[11.0] muk_dms deleting attachments during Document Migration 

### ISSUE THREAD

**Issue by amirpadilla** [muk-it/muk_dms#80]
Hello @Kerrim- @keshrath 

I notice something during the document migration, files are deleted instead of migrating them.

Steps to reproduce:

Change Storage Location from Muk Documents to File Storage and click save
![1](https://user-images.githubusercontent.com/42611243/56314381-e88f5280-6122-11e9-958e-ddc986186a74.png)

Go to the Attachment menu and locate one attachment, in this case we have two Deal Memos that are attachments in the hr.employee model
![2](https://user-images.githubusercontent.com/42611243/56314460-29876700-6123-11e9-8a09-4b1ef1d46791.png)
![3](https://user-images.githubusercontent.com/42611243/56314472-2ee4b180-6123-11e9-929c-b7ce77333ea8.png)

Start the migration of the documents
![4](https://user-images.githubusercontent.com/42611243/56314491-3b690a00-6123-11e9-8a83-73f55b90b06e.png)

 Once Finished the migration, attachments are lost from the MUK menu and from the original place
![5](https://user-images.githubusercontent.com/42611243/56314539-5d628c80-6123-11e9-83a3-f593ffba876c.png)
![6](https://user-images.githubusercontent.com/42611243/56314551-62bfd700-6123-11e9-8af5-7ccf6b70bc1c.png)

Even if I search the name of the document it doesn't show
![7](https://user-images.githubusercontent.com/42611243/56314582-74a17a00-6123-11e9-842b-97a54901e3c3.png)

My question is: How can I migrate the documents without losing them? I need to migrate the attachments and keep them, to be able to uninstall the module.

Related with #79 because I thinks that is what is happening, with the less files.

Regards,
Amir

**Comment by amirpadilla** [comment]
Any update on this?

**Comment by Kerrim-** [comment]
Hi,

I did some testing but I still can't reproduce this error. Does this also happen to you on a new database?
And if so can you also post the version numbers of your modules?

**Comment by amirpadilla** [comment]
Hi @Kerrim- I will try in a new database.

Modules Versions:
MuK Documents - 11.0.2.1.6
MuK Documments Attachments - 11.0.2.0.3

![image](https://user-images.githubusercontent.com/42611243/56757210-ab017980-6761-11e9-87a2-cce2bd765308.png)

**Comment by amirpadilla** [comment]
Hi @Kerrim- 

Tried in a clean environment got the same error.

System:
Odoo 11 CE

Modules Installed:
Employee Directory (hr)
Attachments List and Document Indexation (document)
MuK Documents
MuK Documents Attachment
MuK Documents Attachment Automation

Steps:
**1.- Configure MUK DMS**
- Settings
![image](https://user-images.githubusercontent.com/42611243/56830979-e1a8c400-6835-11e9-8d7c-c8f474dd9cf8.png)
- Root Dir
![image](https://user-images.githubusercontent.com/42611243/56831000-fab17500-6835-11e9-9b82-d03c4b3fa520.png)
- Change Storage Location to MuK Documents - Unsorted Dir
![image](https://user-images.githubusercontent.com/42611243/56831093-3ba98980-6836-11e9-99e3-0c1fe6e0099b.png)
![image](https://user-images.githubusercontent.com/42611243/56831140-5b40b200-6836-11e9-98dd-7a9ac520c306.png)
- Document Structure
![image](https://user-images.githubusercontent.com/42611243/56831175-701d4580-6836-11e9-9d88-e38c702d7295.png)


**2.- Attach Files to Employee**
- Create New Employee
![image](https://user-images.githubusercontent.com/42611243/56831261-9511b880-6836-11e9-8385-7b9ba6e79bd6.png)
-Add Attachments to Employee
![image](https://user-images.githubusercontent.com/42611243/56831297-ae1a6980-6836-11e9-93ab-0a4b9fd45ff0.png)


**3.- Verify Attachments in MuK**
![image](https://user-images.githubusercontent.com/42611243/56831342-c9857480-6836-11e9-91d5-02d29b4ed0ac.png)


**4.- Change Settings for migration / uninstall MuK**
- Change from MuK Documents to File Storage
![image](https://user-images.githubusercontent.com/42611243/56831408-fc2f6d00-6836-11e9-9a52-90c53ba21d17.png)


**5.- Run the migration**
-- From Attachments Run the Migration
![image](https://user-images.githubusercontent.com/42611243/56831468-2a14b180-6837-11e9-85dd-f9e97fd66718.png)

-- Attachments are missing Now in MuK
![image](https://user-images.githubusercontent.com/42611243/56831506-431d6280-6837-11e9-890c-d39a9cf3d182.png)

-- Attachments are missing in Employee as well
![image](https://user-images.githubusercontent.com/42611243/56831549-5b8d7d00-6837-11e9-8e9e-47e9925dd75c.png)



I Got the same result as our production system, there's nothing else installed in the system besides the modules described here.

As you might know the idea is migrate (without losing the attachments) to uninstall MuK DMS.

Please let me know if you need further information about the issue since it's reproducible.

Regards,
Amir

**Comment by amirpadilla** [comment]
@Kerrim- @keshrath Any update on this?

**Comment by keshrath** [comment]
I really couldn't reproduce the error with your instructions, but my guess is that it's muk_dms_file. We rewrote this module for version 12, because there were some problems and under certain circumstances this behavior is also a result of it. Or can you reproduce the error without this module?

**Comment by amirpadilla** [comment]
Hi @keshrath not sure what module are you referring?

These are the modules that I have
![image](https://user-images.githubusercontent.com/42611243/57243323-da3aa500-7003-11e9-89ba-593723e151bd.png)

And 

**Employee Directory (hr)
Attachments List and Document Indexation (document)**

both from Odoo


Do you have an Odoo v11 CE machine where you can test this?
Do you want me to test in Odoo v12? but that won't solve my issue in  v11

Regards,
Amir

**Comment by keshrath** [comment]
What happens if you migrate them one by one?

![image](https://user-images.githubusercontent.com/4851083/57249959-9c12a500-7046-11e9-8609-cfc108d85585.png)

**Comment by amirpadilla** [comment]
@keshrath it does the same. attachment is deleted from the employee

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/blob/11.0/muk_dms_attachment/models/ir_attachment.py#L88

**Comment by amirpadilla** [comment]
@keshrath Not sure what should I be looking in the code, but yes even with one attachment it deletes it from muk documents and from the employee record.

**Comment by amirpadilla** [comment]
@Kerrim- @keshrath 

Video Example

https://bpmint-my.sharepoint.com/:v:/p/apadilla/Eb1XfmWpau5JnR15WMbLP8QBmIZBnbnkGoJTUfKKPI9Mpw?e=Oy3fDZ

**Comment by keshrath** [comment]
This is the code executed by the action. Also in your video, but I can do the same steps and don't get the same result. The code doesn't delete the attachment either, because nowhere is unlink called. You can try to debug the Python code and see what happens when you trigger the action. Maybe you can find the place where the attachment is deleted.

**Comment by keshrath** [comment]
Take a look at `@profile` https://www.odoo.com/documentation/11.0/howtos/profilecode.html

**Comment by amirpadilla** [comment]
Hi @keshrath @Kerrim- any update on this besides me trying to debug the code?

**Comment by amirpadilla** [comment]
@Kerrim- @keshrath Can you send me the latest versions of my MUK Modules to check if something changed?

https://user-images.githubusercontent.com/42611243/57243323-da3aa500-7003-11e9-89ba-593723e151bd.png


Thanks,
Amir

**Comment by keshrath** [comment]
Github has the newest versions.

**Comment by amirpadilla** [comment]
> Github has the newest versions.

@keshrath Can you please add me to the repositories (privates) of the paid modules that I have, so I can update the whole suit.

Thanks,
Amir

**Comment by keshrath** [comment]
For the paid modules you can download them again from the Odoo store. I just updated them again to make sure the are up to date.
