### ISSUE TITLE
MuK Documents View Error on odoo 12 canno't acces to setting after installation

### ISSUE THREAD

**Issue by turkimaki** [muk-it/muk_dms#81]
hello , 
After installing MuK Documents View in Odoo 12 i cann't acces to setting odoo so I just uninstall the module after than setting work .on odoo apps it's noted that " WORK IN PROGRESS ALPHA VERSION!!! " so this problem will be fix soon i hope.
Another thing I want to ask about Muk Document Share now available only for 11 it will be soon for version 12 ?
Thanks .

**Comment by keshrath** [comment]
The settings shouldn't break with the view. Are you sure all the dependecies were up to date?

**Comment by turkimaki** [comment]
Hello yes sir i'am sure

**Comment by PluviaCon** [comment]
I also encountered this problem, using the developer mode, you can not access the settings.
Detailed error:
```js
Tour Manager is ready.  running_tour=null       web.assets_common.js:3456 
warning: Some modules could not be started   web.assets_common.js:3456 
Missing dependencies:    
 (2) ["web_settings_dashboard", "muk_dms_view.DocumentTreeDialogView"]0: "web_settings_dashboard"1: "muk_dms_view.DocumentTreeDialogView"length: 2__proto__: Array(0) 
                                                                                               web.assets_common.js:3460 
Non loaded modules:      
 (2) ["iap.Dashboard", "muk_dms_dialogs.DocumentDirectorySelectionDialog"]0: "iap.Dashboard"1: "muk_dms_dialogs.DocumentDirectorySelectionDialog"length: 2__proto__: Array(0) 
                                                                                              web.assets_common.js:3461 
Debug:          
 {iap.Dashboard: {…}, muk_dms_dialogs.DocumentDirectorySelectionDialog: {…}}
```

Will these modules be missing?

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/commit/4e001888a5425088374c1307f2fcbe9dee25f5dc
