### ISSUE TITLE
Missing „client action“ muk_dms_views.documents

### ISSUE THREAD

**Issue by ehrenstein-c** [muk-it/muk_dms#82]
![Screenshot 2019-04-27 08 46 13](https://user-images.githubusercontent.com/938955/56845980-70b2ec00-68c9-11e9-865c-a041689991e3.png)
I took the copy-into-addons-folder route of installing muk_dms, and after cobbling together the additional apps from various git packages to satisfy all dependencies (and after defining the proper access permissions), I got the error message shown in the screenshot.
Did I miss a package?
I'm on Odoo 11.

**Comment by keshrath** [comment]
There can be a whole lot of reasons for that. Sometimes it helps to restart the server and update the app again, as well as switch to the assets mode (?debug=assets). Possibly it is a problem with the permissions on the operating system, make sure that Odoo has permissions on the corresponding folders. Does all this help nothing look in debug mode with assets to see if you see an error message in the browser console.
