### ISSUE TITLE
Need help: set the default directory for kanban view

### ISSUE THREAD

**Issue by Tikanya** [muk-it/muk_dms#84]
Could you please help how to change the default kanban view from “All” to “My Directory”?

**Comment by keshrath** [comment]
I don't get what you are trying to do

**Comment by Tikanya** [comment]
I would like to specify a directory, selected by default instead of the filter "All" for the model=muk_dms.file&view_type=kanban
if it's possible

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_web/blob/12.0/muk_web_searchpanel/static/src/js/kanban_view.js#L64
