### ISSUE TITLE
[12.0] Problems with setting up Parent Directory

### ISSUE THREAD

**Issue by miguelsilvazup** [muk-it/muk_dms#91]
I'm trying to reconfigure a directory from root directory to an ordinary directory. When I deselect "Is root directory", it opens automatically "Parent directory" to be chosen. But it gives no option of any directory I've created before, only "create and edit".

I expected my other directories were available to move and change the directory structure.

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/commit/5551b9134140c3afe70b53fd4a3c69955ae2ffba

**Comment by miguelsilvazup** [comment]
When I tried to install it, I received the following messages. I tried other procedures before sending you the error, but they didn't work and didn't add any new information.

> Erro:
> 
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 1108, in _validate_fields
>     check(self)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
>     self.postprocess_and_fields(view.model, view_doc, view.id)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 1096, in postprocess_and_fields
>     self.raise_view_error(message, view_id)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
>     raise ValueError(message)
> ValueError: O campo `module_muk_dms_index` não existe
> 
> Contexto de erro:
> Veja `res.config.settings.view.form.inherit.muk_dms`
> [view_id: 1277, xml_id: muk_dms.res_config_settings_view_form, model: res.config.settings, parent_id: 153]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 757, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 662, in _tag_record
>     record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3811, in _load_records
>     data['record']._load_records_write(data['values'])
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 120, in _load_records_write
>     super(View, self)._load_records_write(values)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3749, in _load_records_write
>     self.write(values)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 41, in write
>     return super(View, self).write(vals)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 444, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3323, in write
>     fields[0].determine_inverse(records)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/fields.py", line 1110, in determine_inverse
>     getattr(records, self.inverse)()
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
>     view.write(data)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 41, in write
>     return super(View, self).write(vals)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 444, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3284, in write
>     self._write(store_vals)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3430, in _write
>     self._validate_fields(vals)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 1112, in _validate_fields
>     raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
> odoo.exceptions.ValidationError: ('Error while validating constraint\n\nO campo `module_muk_dms_index` não existe\n\nContexto de erro:\nVeja `res.config.settings.view.form.inherit.muk_dms`\n[view_id: 1277, xml_id: muk_dms.res_config_settings_view_form, model: res.config.settings, parent_id: 153]', None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 654, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 312, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 696, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 344, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 337, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 939, in __call__
>     return self.method(*args, **kw)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 517, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/web/controllers/main.py", line 966, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/api.py", line 749, in call_kw
>     return _call_kw_multi(method, model, args, kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/api.py", line 736, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "<decorator-gen-67>", line 2, in button_immediate_upgrade
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
>     return method(self, *args, **kwargs)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_module.py", line 613, in button_immediate_upgrade
>     return self._button_immediate_function(type(self).button_upgrade)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_module.py", line 552, in _button_immediate_function
>     modules.registry.Registry.new(self._cr.dbname, update_module=True)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/registry.py", line 86, in new
>     odoo.modules.load_modules(registry._db, force_demo, status, update_module)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/loading.py", line 417, in load_modules
>     force, status, report, loaded_modules, update_module, models_to_check)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/loading.py", line 313, in load_marked_modules
>     perform_checks=perform_checks, models_to_check=models_to_check
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/loading.py", line 222, in load_module_graph
>     load_data(cr, idref, mode, kind='data', package=package, report=report)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/loading.py", line 68, in load_data
>     tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 801, in convert_file
>     convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 864, in convert_xml_import
>     obj.parse(doc.getroot(), mode=mode)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 763, in parse
>     exc_info[2]
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/pycompat.py", line 86, in reraise
>     raise value.with_traceback(tb)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 757, in parse
>     self._tags[rec.tag](rec, de, mode=mode)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 662, in _tag_record
>     record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3811, in _load_records
>     data['record']._load_records_write(data['values'])
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 120, in _load_records_write
>     super(View, self)._load_records_write(values)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3749, in _load_records_write
>     self.write(values)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 41, in write
>     return super(View, self).write(vals)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 444, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3323, in write
>     fields[0].determine_inverse(records)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/fields.py", line 1110, in determine_inverse
>     getattr(records, self.inverse)()
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
>     view.write(data)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 41, in write
>     return super(View, self).write(vals)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 444, in write
>     return super(View, self).write(self._compute_defaults(vals))
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3284, in write
>     self._write(store_vals)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3430, in _write
>     self._validate_fields(vals)
>   File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 1112, in _validate_fields
>     raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
> odoo.tools.convert.ParseError: "Error while validating constraint
> 
> O campo `module_muk_dms_index` não existe
> 
> Contexto de erro:
> Veja `res.config.settings.view.form.inherit.muk_dms`
> [view_id: 1277, xml_id: muk_dms.res_config_settings_view_form, model: res.config.settings, parent_id: 153]
> None" while parsing /opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/muk_dms/views/res_config_settings.xml:22, near
> <record id="res_config_settings_view_form" model="ir.ui.view">
> 	<field name="name">res.config.settings.view.form.inherit.muk_dms</field>
> 	<field name="model">res.config.settings</field>
> 	<field name="priority" eval="20"/>
> 	<field name="inherit_id" ref="base.res_config_settings_view_form"/>
> 	<field name="arch" type="xml">
> 	    <xpath expr="//div[hasclass('settings')]" position="inside">
>             <div class="app_settings_block" data-string="Documents" data-key="muk_dms" groups="base.group_system">
>             	<div name="muk_dms_settings">
> 	            	<h2>Extensions</h2>
> 	            	<div class="row mt16 o_settings_container" name="extensions">
> 	            		<div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_access"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_access"/>
> 	                            <div class="text-muted">
> 	                                Allows the creation of groups to define access rights
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_access','=',False)]}" id="msg_module_muk_dms_access">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_mail"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_mail"/>
> 	                            <div class="text-muted">
> 	                                Adds support for messages and activities on directories and files
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_mail','=',False)]}" id="msg_module_muk_dms_mail">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_version"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_version"/>
> 	                            <div class="text-muted">
> 	                                Enables version control for files
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_version','=',False)]}" id="msg_module_muk_dms_version">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_trash"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_trash"/>
> 	                            <div class="text-muted">
> 	                                Activates a file trash to restore deleted files
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_trash','=',False)]}" id="msg_module_muk_dms_trash">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_thumbnails"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_thumbnails"/>
> 	                            <div class="text-muted">
> 	                                Automatically create file thumbnails based on the content
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_thumbnails','=',False)]}" id="msg_module_muk_dms_thumbnails">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_index"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_index"/>
> 	                            <div class="text-muted">
> 	                                Automatically create a file index based on the content
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_index','=',False)]}" id="msg_module_muk_dms_index">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_widget"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_widget"/>
> 	                            <div class="text-muted">
> 	                                Allows the user to use documents as input for any binary field
> 	                            </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_archive"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_archive"/>
> 	                            <div class="text-muted">
> 	                                Allows to download directories as a archive file
> 	                            </div>
> 	                        </div>
> 	                    </div>
> 	                </div>
> 	                <h2>Views</h2>
> 	            	<div class="row mt16 o_settings_container" name="views">
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_preview"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_preview"/>
> 	                            <div class="text-muted">
> 	                                Activates the preview function on files
> 	                            </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_view"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_view"/>
> 	                            <div class="text-muted">
> 	                                Activates the documents tree view
> 	                            </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_finder"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_finder"/>
> 	                            <div class="text-muted">
> 	                                Enables the Document Finder
> 	                            </div>
> 	                        </div>
> 	                    </div>
> 	                </div>
> 	                <h2>Storage</h2>
> 	            	<div class="row mt16 o_settings_container" name="storages">
> 	            		<div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_lobject"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_lobject"/>
> 	                            <div class="text-muted">
> 	                                Enables a new save option to store files into large objects
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_lobject','=',False)]}" id="msg_module_muk_dms_lobject">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	            		<div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_file"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_file"/>
> 	                            <div class="text-muted">
> 	                                Enables a new save option to store files into a filestore
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_file','=',False)]}" id="msg_module_muk_dms_file">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                </div>
> 	                <h2>Attachments</h2>
> 	            	<div class="row mt16 o_settings_container" name="attachments">
> 	            		<div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_attachment"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_attachment"/>
> 	                            <div class="text-muted">
> 	                                Allows attachments to be stored inside of Documents
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_attachment','=',False)]}" id="msg_module_muk_dms_attachment">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	            		<div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_attachment_wizard"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_attachment_wizard"/>
> 	                            <div class="text-muted">
> 	                                Allows documents to be used as attachments
> 	                            </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_attachment_rules"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_attachment_rules"/>
> 	                            <div class="text-muted">
> 	                                Allows to placed attachments in the right directory
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_attachment_rules','=',False)]}" id="msg_module_muk_dms_attachment_rules">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_attachment_automation"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_attachment_automation"/>
> 	                            <div class="text-muted">
> 	                                Allows you to create rule templates to create attachment rules
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_attachment_automation','=',False)]}" id="msg_module_muk_dms_attachment_automation">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                </div>
> 	                <h2>Integrations</h2>
> 	            	<div class="row mt16 o_settings_container" name="integrations">
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_actions"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_actions"/>
> 	                            <div class="text-muted">
> 	                                Create custom file operations
> 	                            </div>
> 		                        <div class="content-group" attrs="{'invisible': [('module_muk_dms_actions','=',False)]}" id="msg_module_muk_dms_actions">
> 		                            <div class="text-warning mt16"><strong>Save</strong> this page and come back here to set up the feature.</div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-lg-6 o_setting_box">
> 	                        <div class="o_setting_left_pane">
> 	                            <field name="module_muk_dms_users"/>
> 	                        </div>
> 	                        <div class="o_setting_right_pane">
> 	                            <label for="module_muk_dms_users"/>
> 	                            <div class="text-muted">
> 	                                Automatic creation of user directories
> 	                            </div>
> 	                        </div>
> 	                    </div>
> 	                </div>
> 	                <h2>File Upload</h2>
> 	                <div class="row mt16 o_settings_container" name="file">
> 	                    <div class="col-12 col-md-6 o_setting_box">
> 	                        <div class="o_setting_right_pane">
> 	                            <span class="o_form_label">File Size</span>
> 	                            <div class="text-muted">
> 	                                Define the maximum upload size of a file in MB
> 	                            </div>
> 	                            <div class="content-group">
> 		                            <div class="row mt16">
> 		                                <label class="col-md-3 o_light_label" for="documents_binary_max_size"/>
> 		                                <field name="documents_binary_max_size"/>
> 		                            </div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                    <div class="col-12 col-md-6 o_setting_box">
> 	                        <div class="o_setting_right_pane">
> 	                            <span class="o_form_label">File Extensions</span>
> 	                            <div class="text-muted">
> 	                                Define forbidden file extensions
> 	                            </div>
> 	                            <div class="content-group">
> 		                            <div class="row mt16">
> 		                                <label class="col-md-3 o_light_label" for="documents_forbidden_extensions"/>
> 		                                <field name="documents_forbidden_extensions" placeholder="exe,msi"/>
> 		                            </div>
> 		                        </div>
> 	                        </div>
> 	                    </div>
> 	                </div>
>                 </div>
>             </div>
>     	</xpath>
>     </field>
> </record>
