### ISSUE TITLE
Document migration with drag and drop (move) does not delete file in filesystem and not fill content_binary column in database

### ISSUE THREAD

**Issue by bolatk** [muk-it/muk_dms#92]
I am using the latest version of MUK DMS module.
Steps to reproduce the issue:

1. Move any file from a folder with Filesystem storage to any folder with Document storage.
2. Check **content_binary**, **content_file** columns in `muk_dms_file` PostgreSQL table.

When you do **Migration** action manually, following the Configuration-System-Migration menu, migrated file stays corrupted with **zero** byte file size.

**Comment by Kerrim-** [comment]
Which Odoo version are you using?

**Comment by bolatk** [comment]
> Which Odoo version are you using?

Sorry, Odoo 12.

**Comment by keshrath** [comment]
https://github.com/muk-it/muk_dms/commit/6fc046928638d10d7210027de10f1ffe46eb8f41 | https://github.com/muk-it/muk_dms/commit/d55686aca773358d2fed45245584038747358afb | https://github.com/muk-it/muk_dms/commit/b43eff3a506b59d398cc713063f2955eec400da5
