### ISSUE TITLE
Installation von muk_web_security führt zu Style Error

### ISSUE THREAD

**Issue by ehrenstein-c** [muk-it/muk_dms#94]
Ich habe beim Versuch der Installation von zahlreichen MuK-Paketen (insbesondere DMS) ein Problem mit Style-Fehlern, konnte das Problem aber schließlich auf das Paket muk_web_security eingrenzen, nach dessen Installation der folgende Fehler erstmalig auftaucht:

`The style compilation failed, see the error below. Your recent actions may be the cause, please try reverting the changes you made.

NameError: variable @odoo-main-color-muted is undefined in - on line 44, column 9:
43 .locked {
44 	color: @odoo-main-color-muted;
45 	

This error occured while compiling the bundle 'web.assets_backend' containing:
    - /web/static/lib/bootstrap/scss/_functions.scss
    - /web/static/lib/bootstrap/scss/_mixins.scss
    - /web/static/src/scss/utils.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /muk_web_theme/static/src/scss/mixins.scss
    - /web/static/src/scss/primary_variables.scss
    - /muk_web_theme/static/src/scss/colors.scss
    - /web_editor/static/src/scss/web_editor.variables.scss
    - /mail/static/src/scss/variables.scss
    - /portal/static/src/scss/primary_variables.scss
    - /web/static/src/scss/secondary_variables.scss
    - /account/static/src/scss/variables.scss
    - /web/static/src/scss/bootstrap_overridden.scss
    - /muk_web_theme/static/src/scss/variables.scss
    - /web_editor/static/src/scss/bootstrap_overridden.scss
    - /web/static/src/scss/import_bootstrap_part1.scss
    - /web/static/src/scss/bs_mixins_overrides.scss
    - /web/static/src/scss/import_bootstrap_part2.scss
    - /web/static/src/scss/bootstrap_review.scss
    - /web/static/src/scss/webclient_extra.scss
    - /web/static/src/scss/webclient_layout.scss
    - /web/static/src/scss/webclient.scss
    - /web/static/src/scss/domain_selector.scss
    - /web/static/src/scss/model_field_selector.scss
    - /web/static/src/scss/progress_bar.scss
    - /web/static/src/scss/dropdown.scss
    - /web/static/src/scss/dropdown_extra.scss
    - /web/static/src/scss/tooltip.scss
    - /web/static/src/scss/debug_manager.scss
    - /web/static/src/scss/control_panel.scss
    - /web/static/src/scss/fields.scss
    - /web/static/src/scss/fields_extra.scss
    - /web/static/src/scss/views.scss
    - /web/static/src/scss/pivot_view.scss
    - /web/static/src/scss/graph_view.scss
    - /web/static/src/scss/form_view.scss
    - /web/static/src/scss/form_view_extra.scss
    - /web/static/src/scss/list_view.scss
    - /web/static/src/scss/list_view_extra.scss
    - /web/static/src/scss/kanban_dashboard.scss
    - /web/static/src/scss/kanban_examples_dialog.scss
    - /web/static/src/scss/kanban_column_progressbar.scss
    - /web/static/src/scss/kanban_view.scss
    - /web/static/src/scss/kanban_view_mobile.scss
    - /web/static/src/scss/web_calendar.scss
    - /web/static/src/scss/search_view.scss
    - /web/static/src/scss/search_view_mobile.scss
    - /web/static/src/scss/dropdown_menu.scss
    - /web/static/src/scss/search_view_extra.scss
    - /web/static/src/scss/data_export.scss
    - /base/static/src/scss/onboarding.scss
    - /web/static/src/scss/base_settings.scss
    - /web/static/src/scss/report_backend.scss
    - /base_import/static/src/scss/base_import.scss
    - /web_diagram/static/src/scss/diagram_view.scss
    - /web_editor/static/src/scss/web_editor.common.scss
    - /web_editor/static/src/scss/web_editor.backend.scss
    - /mail/static/src/scss/announcement.scss
    - /mail/static/src/scss/discuss.scss
    - /mail/static/src/scss/abstract_thread_window.scss
    - /mail/static/src/scss/thread_window.scss
    - /mail/static/src/scss/composer.scss
    - /mail/static/src/scss/chatter.scss
    - /mail/static/src/scss/followers.scss
    - /mail/static/src/scss/thread.scss
    - /mail/static/src/scss/systray.scss
    - /mail/static/src/scss/mail_activity.scss
    - /mail/static/src/scss/activity_view.scss
    - /mail/static/src/scss/kanban_view.scss
    - /mail/static/src/scss/attachment_box.scss
    - /calendar/static/src/scss/calendar.scss
    - /sales_team/static/src/scss/sales_team_dashboard.scss
    - /note/static/src/scss/note.scss
    - /hr/static/src/scss/hr.scss
    - /project/static/src/scss/project_dashboard.scss
    - /account/static/src/scss/account_reconciliation.scss
    - /account/static/src/scss/account_journal_dashboard.scss
    - /account/static/src/scss/account_dashboard.scss
    - /account/static/src/scss/section_and_note_backend.scss
    - /payment/static/src/scss/payment_acquirer.scss
    - /om_account_asset/static/src/scss/account_asset.scss
    - /stock/static/src/scss/stock_traceability_report.scss
    - /sale/static/src/scss/sale_onboarding.scss
    - /sale/static/src/scss/product_configurator.scss
    - /sale_timesheet/static/src/scss/sale_timesheet.scss
    - /hr_holidays/static/scss/hr_leave_mobile.scss
    - /hr_attendance/static/src/scss/hr_attendance.scss
    - /board/static/src/scss/dashboard.scss
    - /muk_web_utils/static/src/scss/variables.scss
    - /muk_web_utils/static/src/scss/mixins.scss
    - /muk_web_utils/static/src/scss/switch.scss
    - /muk_web_utils/static/src/scss/dropzone.scss
    - /muk_web_utils/static/src/scss/module.scss
    - /muk_web_utils/static/src/scss/color.scss
    - /muk_web_utils/static/src/scss/binary.scss
    - /muk_web_utils/static/src/scss/image.scss
    - /muk_web_utils/static/src/scss/copy.scss
    - /muk_web_utils/static/src/scss/share.scss
    - /muk_web_utils/static/src/scss/notification.scss
    - /muk_web_theme/static/src/scss/layout.scss
    - /muk_web_theme/static/src/scss/navbar.scss
    - /muk_web_theme/static/src/scss/apps.scss
    - /muk_web_theme/static/src/scss/appsbar.scss
    - /muk_web_theme/static/src/scss/control_panel.scss
    - /muk_web_theme/static/src/scss/list_view.scss
    - /muk_web_theme/static/src/scss/form_view.scss
    - /muk_web_theme/static/src/scss/fields.scss
    - /muk_web_theme/static/src/scss/notification.scss
    - /muk_web_theme/static/src/scss/settings.scss
    - /muk_web_theme_mail/static/src/scss/chatter.scss
    - /muk_web_security/static/src/less/views_list.less
    - /muk_web_searchpanel/static/src/scss/variables.scss
    - /muk_web_searchpanel/static/src/scss/kanban_view.scss
    - /muk_dms/static/src/scss/variables.scss
    - /muk_dms/static/src/scss/directory_kanban.scss
    - /muk_dms/static/src/scss/file_kanban.scss
    - /web_settings_dashboard/static/src/scss/dashboard.scss`

**Comment by keshrath** [comment]
Dein Fehler Log sieht nach Odoo 12.0 aus. Das Modul muk_web_security existiert aber für diese Version gar nicht.

**Comment by ehrenstein-c** [comment]
Hmm… strange.
Was ich gemacht habe:

- die Pakete von GitHub, in einem weiteren Versuch auch vom Nexus-Server runtergeladen
- muk_dms installiert --> Fehler taucht auf
- mich an den Deps entlanggehangelt, bis der Fehler auftaucht --> bei Installation von muk_security wurde dann muk_web_security mitinstalliert.

Habe ich vielleicht eine veraltete Dependency-Referenzdatei bei mir auf dem Server, dass Odoo überhaupt muk_web_security installiert? Ich habe nämlich im Modul selbst nichts gefunden.

Außerdem habe ich jetzt einmal alles paketweise installiert, was für muk_dms als Voraussetzung angegeben ist, und jetzt bleibt der Fehler auch aus.

**Comment by keshrath** [comment]
Sprich du hast jetzt keinen Fehler mehr?

**Comment by ehrenstein-c** [comment]
Es scheint so. Wenn ich aber alles von MuK deinstalliere und direkt muk_dms installiere, taucht der Fehler wieder auf. Da muss also irgendwo noch eine Dep drinstehen, die Odoo dazu veranlasst, muk_web_security zu installieren.

**Comment by keshrath** [comment]
Also in den Version 12.0 Modulen gibts diese Abhängigkeit nicht. Vielleicht hast du irgendwo irrtümlich ein Modul von 11.0 mit drin. 

Für mich hat sich gezeigt, dass es am Besten ist die Module über `pip` zu installieren. Dann musst du dir über die Abhängigkeiten auch keine Gedanken mehr machen.

Nexus: https://nexus.mukit.at/#browse/browse:odoo
Info: https://mukit.at/en_US/page/open-source (am Ende der Seite)

**Comment by keshrath** [comment]
`muk_web_security` hat einen `auto install` Flag sprich es wird installiert sobald die Abhängigkeiten erfüllt sind. Ergo sobald `muk_security` installiert ist. Das Modul sollte aber gar nicht in deinem Addons Ordner sein, weil es nicht die richtige Version hat. 

Code: https://github.com/muk-it/muk_web/blob/11.0/muk_web_security/__manifest__.py#L50

**Comment by keshrath** [comment]
Ich werde dieses Ticket schließen da es seit einer Woche keine neuen Informationen gibt. Falls du weitere Probleme hast öffne bitte ein neues Ticket.
