### ISSUE TITLE
[12.0] muk_dms installation 

### ISSUE THREAD

**Issue by miguelsilvazup** [muk-it/muk_dms#95]
When I tried to install the newest version of muk_dms, I received the following message. I tried other procedures before sending you the error, but they didn't work and didn't add any new information.

> Erro:
> 
> Odoo Server Error
> 
> Traceback (most recent call last):
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 1108, in _validate_fields
> check(self)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
> self.postprocess_and_fields(view.model, view_doc, view.id)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 1096, in postprocess_and_fields
> self.raise_view_error(message, view_id)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
> raise ValueError(message)
> ValueError: O campo module_muk_dms_index não existe
> 
> Contexto de erro:
> Veja res.config.settings.view.form.inherit.muk_dms
> [view_id: 1277, xml_id: muk_dms.res_config_settings_view_form, model: res.config.settings, parent_id: 153]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 757, in parse
> self._tags[rec.tag](rec, de, mode=mode)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 662, in _tag_record
> record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3811, in _load_records
> data['record']._load_records_write(data['values'])
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 120, in _load_records_write
> super(View, self)._load_records_write(values)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3749, in _load_records_write
> self.write(values)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 41, in write
> return super(View, self).write(vals)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 444, in write
> return super(View, self).write(self._compute_defaults(vals))
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3323, in write
> fields[0].determine_inverse(records)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/fields.py", line 1110, in determine_inverse
> getattr(records, self.inverse)()
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
> view.write(data)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 41, in write
> return super(View, self).write(vals)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 444, in write
> return super(View, self).write(self._compute_defaults(vals))
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3284, in write
> self._write(store_vals)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3430, in _write
> self._validate_fields(vals)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 1112, in validate_fields
> raise ValidationError("%s\n\n%s" % (("Error while validating constraint"), tools.ustr(e)))
> odoo.exceptions.ValidationError: ('Error while validating constraint\n\nO campo module_muk_dms_index não existe\n\nContexto de erro:\nVeja res.config.settings.view.form.inherit.muk_dms\n[view_id: 1277, xml_id: muk_dms.res_config_settings_view_form, model: res.config.settings, parent_id: 153]', None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 654, in _handle_exception
> return super(JsonRequest, self)._handle_exception(exception)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 312, in _handle_exception
> raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
> raise value
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 696, in dispatch
> result = self._call_function(**self.params)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 344, in _call_function
> return checked_call(self.db, *args, **kwargs)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/service/model.py", line 97, in wrapper
> return f(dbname, *args, **kwargs)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 337, in checked_call
> result = self.endpoint(*a, **kw)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 939, in call
> return self.method(*args, **kw)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/http.py", line 517, in response_wrap
> response = f(*args, **kw)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/web/controllers/main.py", line 966, in call_button
> action = self._call_kw(model, method, args, {})
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
> return call_kw(request.env[model], method, args, kwargs)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/api.py", line 749, in call_kw
> return _call_kw_multi(method, model, args, kwargs)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/api.py", line 736, in _call_kw_multi
> result = method(recs, *args, **kwargs)
> File "", line 2, in button_immediate_upgrade
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_module.py", line 73, in check_and_log
> return method(self, *args, **kwargs)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_module.py", line 613, in button_immediate_upgrade
> return self._button_immediate_function(type(self).button_upgrade)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_module.py", line 552, in _button_immediate_function
> modules.registry.Registry.new(self._cr.dbname, update_module=True)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/registry.py", line 86, in new
> odoo.modules.load_modules(registry._db, force_demo, status, update_module)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/loading.py", line 417, in load_modules
> force, status, report, loaded_modules, update_module, models_to_check)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/loading.py", line 313, in load_marked_modules
> perform_checks=perform_checks, models_to_check=models_to_check
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/loading.py", line 222, in load_module_graph
> load_data(cr, idref, mode, kind='data', package=package, report=report)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/modules/loading.py", line 68, in load_data
> tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 801, in convert_file
> convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 864, in convert_xml_import
> obj.parse(doc.getroot(), mode=mode)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 763, in parse
> exc_info[2]
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/pycompat.py", line 86, in reraise
> raise value.with_traceback(tb)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 757, in parse
> self._tags[rec.tag](rec, de, mode=mode)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/tools/convert.py", line 662, in _tag_record
> record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3811, in _load_records
> data['record']._load_records_write(data['values'])
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 120, in _load_records_write
> super(View, self)._load_records_write(values)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3749, in _load_records_write
> self.write(values)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 41, in write
> return super(View, self).write(vals)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 444, in write
> return super(View, self).write(self._compute_defaults(vals))
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3323, in write
> fields[0].determine_inverse(records)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/fields.py", line 1110, in determine_inverse
> getattr(records, self.inverse)()
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
> view.write(data)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/website/models/ir_ui_view.py", line 41, in write
> return super(View, self).write(vals)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 444, in write
> return super(View, self).write(self._compute_defaults(vals))
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3284, in write
> self._write(store_vals)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 3430, in _write
> self._validate_fields(vals)
> File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/models.py", line 1112, in validate_fields
> raise ValidationError("%s\n\n%s" % (("Error while validating constraint"), tools.ustr(e)))
> odoo.tools.convert.ParseError: "Error while validating constraint
> 
> O campo module_muk_dms_index não existe
> 
> Contexto de erro:
> Veja res.config.settings.view.form.inherit.muk_dms
> [view_id: 1277, xml_id: muk_dms.res_config_settings_view_form, model: res.config.settings, parent_id: 153]
> None" while parsing /opt/bitnami/apps/odoo/lib/odoo-12.0.post20190318-py3.7.egg/odoo/addons/muk_dms/views/res_config_settings.xml:22, near
> 
> res.config.settings.view.form.inherit.muk_dms
> res.config.settings

**Comment by keshrath** [comment]
Seems to me that you are missing module_muk_dms_index in your database:

https://github.com/muk-it/muk_dms/blob/12.0/muk_dms/models/res_config_settings.py#L58
