### ISSUE TITLE
[11.0] Regression muk_dms_file: database operations broken on databases that have not muk_dms_file installed.

### ISSUE THREAD

**Issue by katyukha** [muk-it/muk_dms#96]
Regression is here:
![image](https://user-images.githubusercontent.com/1129820/60114118-cf86cb80-977b-11e9-99c0-449011417c62.png)

Statement `if env.get('muk_dms.settings')` checks whether muk_dms is installed on this database (if 'muk_dms.settings' model is present in registry).

In case, when you have server with two databases: one with muk_dms_file installed and second without, then it is not possible to duplicate/backup/drop/etc second database.

**Comment by Kerrim-** [comment]
https://github.com/muk-it/muk_dms/commit/caa6d3498d156ef9d15f40e52c0b8c88a7f422f5 should fix this. Can you confirm?

Thanks for reporting!

**Comment by katyukha** [comment]
Thank you for so fast reaction)
I will check it today.

**Comment by katyukha** [comment]
Diff shows me that file is completely rewritten. Is it correct?

Also, check this part of diff:
![image](https://user-images.githubusercontent.com/1129820/60256309-f3f8ba00-98d9-11e9-8f03-c7617c7cb273.png)

is following change correct?
![image](https://user-images.githubusercontent.com/1129820/60256363-096de400-98da-11e9-848b-d9d48cdd5dea.png)

**Comment by Kerrim-** [comment]
Now everything should be working fine.

https://github.com/muk-it/muk_dms/commit/afe20f7a08ec95aa0e287228caea6b6fea8eff1d
