### ISSUE TITLE
Cannot copy/past multiple selected files

### ISSUE THREAD

**Issue by jiangweiatgithub** [muk-it/muk_dms#97]
Hi,
I can select/highlight multiple files, but when I try taking some action from the context menu, such as copy, delete, etc, only the only file that my mouse is hovering over is acted upon.  Is that designed so, or can I have other options to act on multiple selected files? (I can drag and drop multiple "nodes", though.)

Actually, I also want to reference all the multiple selected files in a server script. Can I ? (For the comment, I have managed to use "record.content_file" to reference to the only file that the mouse is hovering over.

Thanks,
Wei

**Comment by jiangweiatgithub** [comment]
Is there anything done about this?

**Comment by keshrath** [comment]
The context menu only works for single files. Only think which works for multiple files is drag and drop as well as the delete button.

**Comment by keshrath** [comment]
I have plans to support multi files for https://github.com/muk-it/muk_dms/tree/12.0/muk_dms_actions but its not visible so far.

**Comment by jiangweiatgithub** [comment]
Any news?
