### ISSUE TITLE
Large PDF files is not uploading

### ISSUE THREAD

**Issue by bhanukiran6688** [muk-it/muk_dms#98]
Hi,
Impacted versions: 11 and 12
In documents view [first menu, may be javascript view], there is an option to upload files. When small files are uploaded there is no issue but when files greater that 12MB are uploaded, the upload fails and no error message is shown either in view or in the server logs. Even after waiting for 10 minutes, the uploaded file doesn't show in the documents list. This is reproducible in MUK demo server.

**Comment by dngster** [comment]
Hello, I have also encountered the same issue where the Connection is lost when I tried to upload files about the size of 1 mb.
File size up to 500 kb can be uploaded without any issues.

Not sure if the below error message corresponds to the same issue :
"Bad Request
<function DataSet.call_kw at 0x7f357e312510>, /web/dataset/call_kw/muk_dms.file/create: Function declared as capable of handling request of type 'json' but called with a request of type 'http'"

Appreciate any help and advice on this issue! @keshrath

**Comment by keshrath** [comment]
Can you tell me which upload fails?

**Comment by dngster** [comment]
I have tried docx and pdf file format that are only 1.2mb and 1.9mb yet it failed to upload.
I have just tried creating a docx file that only contains dummy lorem ipsum text at 5.2mb and it fails to upload, showing the same connection lost error message.
It seems that any file upload of 1.0 mb and above would fail.

**Comment by keshrath** [comment]
I mean which view and button. So I can reproduce the steps you took.

**Comment by dngster** [comment]
![Files_Drag_and_Drop](https://user-images.githubusercontent.com/15981974/79234997-a0be1b00-7e9d-11ea-9d15-41a4b6e337b2.png)
![Files_Manual_Create_Upload](https://user-images.githubusercontent.com/15981974/79235005-a3207500-7e9d-11ea-9ce8-9d9e093f3bce.png)
please see attached screenshots. For both methods of uploading by Drag and Drop and Manually uploading the files using the "Create" button, it ended up with the same issue.

**Comment by keshrath** [comment]
The 2. way of uploading uses the standard Odoo binary widget. So you should have the problem not only on the DMS. Might be the case that the problem is actually your web server and the limits set there.

**Comment by dngster** [comment]
@keshrath you are right. the issue was with the limits set on the web server. we have increased it and are able to upload larger file size now. thank you!
