### ISSUE TITLE
Bug on Odoo 9 Entreprise

### ISSUE THREAD

**Issue by fnguena** [muk-it/muk_dms#99]
Hello,
I encounter a bug when I install the muk_dms module on odoo 9e entreprise.
in attachment a print of the bug .... thank you. need help to debug
![bug](https://user-images.githubusercontent.com/12985085/60573705-17a38080-9d70-11e9-9858-40625751c84f.png)

**Comment by Kerrim-** [comment]
I'm sorry like Odoo we only provide support for the last three major odoo versions.

Regards,
Kerrim
